.include "macros.asm"
.include "config.asm"
.include "SLUS_labels.asm"

.include "GameData.asm"
.include "SearchFiles.asm"
.include "Jukebox.asm"
.include "Evolutions.asm"
.include "RaiseDataReloc.asm"
.include "EvoDataReloc.asm"
.include "Softlocks.asm"
.include "Naming.asm"