#include "extern/dtl/array.hpp"

extern "C"
{
    dtl::array<const char*, 70> MAP_NAME_PTR{
        "Native Forest",
        "Coela Point",
        "Dragon Eye Lake",
        "Drill Tunnel Entrance",
        "Digimon Bridge",
        "Tropical Jungle",
        "Mangrove Region",
        "Path Thru Mt. Panorama",
        "Entrance to File City",
        "Mt. Panorama Plains",
        "Foot of Mt. Panorama",
        "Mt. Panorama Spore Area",
        "Drill Tunnel",
        "Drill Tunnel 2nd floor",
        "Drill Tunnel 3rd floor",
        "Residential Area",
        "Underground Pond",
        "Lava Cave",
        "Overdell",
        "Overdell Cemetery",
        "Great Canyon Entrance",
        "Great Canyon Top Area",
        "Great Canyon Bridge",
        "Fortress Entrance",
        "Great Canyon Bot. Area",
        "Ogre Fortress",
        "Monochrome Shop",
        "Grey Lord's Mansion",
        "Mansion Basement",
        "Underground Lab",
        "Gear Savanna",
        "Ancient Dino Region",
        "Ancient Glacial Region",
        "Ancient Speedy Region",
        "Freezeland",
        "Ice Sanctuary",
        "Green Gym",
        "Leomon Ancestor's Cave",
        "Misty Trees",
        "Great Canyon",
        "Freezeland",
        "Geko Swamp",
        "Volume Villa",
        "File City",
        "Item Keeper",
        "Centar Clinic",
        "Restaurant",
        "Item Shop",
        "Jijimon's house",
        "Secret Item Shop",
        "Toy Town",
        "Secret Beach Cave",
        "Factorial Town",
        "Birdra Transport",
        "Arena Lobby",
        "Treasure Hunt",
        "Trash Mountain",
        "Sewer",
        "Beetle Land",
        "Mt. Infinity",
        "Digimon Curling",
        "Toy Mansion",
        "Costume House",
        "Robot House",
        "Mansion 2nd floor",
        "Mansion Attic",
        "Mansion Basement",
        "Back Dimension",
        "Kunemon's Bed",
        "Amida Forest",
    };
}
