#include "StatsViewData.hpp"

#include "UIElements.hpp"

extern "C"
{
    TextSprite labels[] = {
        {
            .font       = &myFont7px,
            .string     = "NAME",
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 80,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 0,
            .posY       = PROFILE_OFFSET_Y + 15,
            .boxWidth   = 30,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 2,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "DIGI",
            .uvX        = DRAW_OFFSET_X + 8,
            .uvY        = DRAW_OFFSET_Y + 80,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 0,
            .posY       = PROFILE_OFFSET_Y + 31,
            .boxWidth   = 30,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 2,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "AGE",
            .uvX        = DRAW_OFFSET_X + 16,
            .uvY        = DRAW_OFFSET_Y + 80,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 0,
            .posY       = PROFILE_OFFSET_Y + 47,
            .boxWidth   = 30,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 2,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "WEIGHT",
            .uvX        = DRAW_OFFSET_X + 24,
            .uvY        = DRAW_OFFSET_Y + 80,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 62,
            .posY       = PROFILE_OFFSET_Y + 47,
            .boxWidth   = 40,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 2,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "BATTLE",
            .uvX        = DRAW_OFFSET_X + 32,
            .uvY        = DRAW_OFFSET_Y + 80,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 134,
            .posY       = PROFILE_OFFSET_Y + 47,
            .boxWidth   = 40,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 2,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "MISTAKE",
            .uvX        = DRAW_OFFSET_X + 40,
            .uvY        = DRAW_OFFSET_Y + 80,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 206,
            .posY       = PROFILE_OFFSET_Y + 47,
            .boxWidth   = 40,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 2,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "LIVES",
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 14,
            .posY       = CONDITION_OFFSET_Y + 34,
            .boxWidth   = 44,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "HAPPINESS",
            .uvX        = DRAW_OFFSET_X + 32,
            .uvY        = DRAW_OFFSET_Y,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 14,
            .posY       = CONDITION_OFFSET_Y + 50,
            .boxWidth   = 44,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "DISCIPLINE",
            .uvX        = DRAW_OFFSET_X + 16,
            .uvY        = DRAW_OFFSET_Y,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 14,
            .posY       = CONDITION_OFFSET_Y + 64,
            .boxWidth   = 44,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "TIREDNESS",
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 68,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 14,
            .posY       = CONDITION_OFFSET_Y + 78,
            .boxWidth   = 44,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "CURSE",
            .uvX        = DRAW_OFFSET_X + 48,
            .uvY        = DRAW_OFFSET_Y,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 14,
            .posY       = CONDITION_OFFSET_Y + 92,
            .boxWidth   = 44,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },

        {
            .font       = &myFont7px,
            .string     = "HP",
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 8,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 14,
            .posY       = STATS_OFFSET_Y + 14,
            .boxWidth   = 18,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "MP",
            .uvX        = DRAW_OFFSET_X + 16,
            .uvY        = DRAW_OFFSET_Y + 8,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 14,
            .posY       = STATS_OFFSET_Y + 29,
            .boxWidth   = 18,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "OFF",
            .uvX        = DRAW_OFFSET_X + 32,
            .uvY        = DRAW_OFFSET_Y + 8,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 14,
            .posY       = STATS_OFFSET_Y + 44,
            .boxWidth   = 18,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "DEF",
            .uvX        = DRAW_OFFSET_X + 48,
            .uvY        = DRAW_OFFSET_Y + 8,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 14,
            .posY       = STATS_OFFSET_Y + 59,
            .boxWidth   = 18,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "SPD",
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 16,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 14,
            .posY       = STATS_OFFSET_Y + 74,
            .boxWidth   = 18,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont7px,
            .string     = "BRN",
            .uvX        = DRAW_OFFSET_X + 16,
            .uvY        = DRAW_OFFSET_Y + 16,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 14,
            .posY       = STATS_OFFSET_Y + 89,
            .boxWidth   = 18,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 3,
            .layer      = 5,
            .hasShadow  = 1,
        },

        {
            .font       = &myFont5px,
            .string     = "SPECIAL",
            .uvX        = DRAW_OFFSET_X + 32,
            .uvY        = DRAW_OFFSET_Y + 16,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 192,
            .posY       = PROFILE_OFFSET_Y + 31,
            .boxWidth   = 32,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 7,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont5px,
            .string     = "TYPE",
            .uvX        = DRAW_OFFSET_X + 40,
            .uvY        = DRAW_OFFSET_Y + 16,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 259,
            .posY       = PROFILE_OFFSET_Y,
            .boxWidth   = 20,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 4,
            .layer      = 5,
            .hasShadow  = 1,
        },
        {
            .font       = &myFont5px,
            .string     = "ACTIVE",
            .uvX        = DRAW_OFFSET_X + 48,
            .uvY        = DRAW_OFFSET_Y + 16,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 192,
            .posY       = PROFILE_OFFSET_Y,
            .boxWidth   = 64,
            .boxHeight  = 14,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 6,
            .layer      = 5,
            .hasShadow  = 1,
        },

    };

    TextSprite values[] = {
        // Name
        {
            .font       = &vanillaFont,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 24,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 34,
            .posY       = PROFILE_OFFSET_Y + 16,
            .boxWidth   = 152,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Digimon
        {
            .font       = &vanillaFont,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 36,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 34,
            .posY       = PROFILE_OFFSET_Y + 32,
            .boxWidth   = 152,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::LEFT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Age
        {
            .font       = &vanillaFont,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 32,
            .uvY        = DRAW_OFFSET_Y + 48,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 34,
            .posY       = PROFILE_OFFSET_Y + 48,
            .boxWidth   = 25,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Weight
        {
            .font       = &vanillaFont,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 40,
            .uvY        = DRAW_OFFSET_Y + 48,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 106,
            .posY       = PROFILE_OFFSET_Y + 48,
            .boxWidth   = 25,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Battles
        {
            .font       = &vanillaFont,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 48,
            .uvY        = DRAW_OFFSET_Y + 48,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 178,
            .posY       = PROFILE_OFFSET_Y + 48,
            .boxWidth   = 25,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Care
        {
            .font       = &vanillaFont,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 56,
            .uvY        = DRAW_OFFSET_Y + 48,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 250,
            .posY       = PROFILE_OFFSET_Y + 48,
            .boxWidth   = 25,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::RIGHT,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Active Time
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 48,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = PROFILE_OFFSET_X + 192,
            .posY       = PROFILE_OFFSET_Y + 16,
            .boxWidth   = 64,
            .boxHeight  = 12,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // HP
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X,
            .uvY        = DRAW_OFFSET_Y + 60,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 34,
            .posY       = STATS_OFFSET_Y + 15,
            .boxWidth   = 77,
            .boxHeight  = 8,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // MP
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 16,
            .uvY        = DRAW_OFFSET_Y + 60,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 34,
            .posY       = STATS_OFFSET_Y + 30,
            .boxWidth   = 77,
            .boxHeight  = 8,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },

        // Offense
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 32,
            .uvY        = DRAW_OFFSET_Y + 60,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 34,
            .posY       = STATS_OFFSET_Y + 45,
            .boxWidth   = 42,
            .boxHeight  = 8,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Defense
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 40,
            .uvY        = DRAW_OFFSET_Y + 60,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 34,
            .posY       = STATS_OFFSET_Y + 60,
            .boxWidth   = 42,
            .boxHeight  = 8,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Speed
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 48,
            .uvY        = DRAW_OFFSET_Y + 60,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 34,
            .posY       = STATS_OFFSET_Y + 75,
            .boxWidth   = 42,
            .boxHeight  = 8,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // Brains
        {
            .font       = &myFont7px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 56,
            .uvY        = DRAW_OFFSET_Y + 60,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = STATS_OFFSET_X + 34,
            .posY       = STATS_OFFSET_Y + 90,
            .boxWidth   = 42,
            .boxHeight  = 8,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::CENTER,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // happiness
        {
            .font       = &myFont5px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 0,
            .uvY        = DRAW_OFFSET_Y + 88,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 62,
            .posY       = CONDITION_OFFSET_Y + 49,
            .boxWidth   = 48,
            .boxHeight  = 6,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // discipline
        {
            .font       = &myFont5px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 8,
            .uvY        = DRAW_OFFSET_Y + 88,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 62,
            .posY       = CONDITION_OFFSET_Y + 63,
            .boxWidth   = 48,
            .boxHeight  = 6,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // tiredness
        {
            .font       = &myFont5px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 16,
            .uvY        = DRAW_OFFSET_Y + 88,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 62,
            .posY       = CONDITION_OFFSET_Y + 77,
            .boxWidth   = 48,
            .boxHeight  = 6,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
        // virus
        {
            .font       = &myFont5px,
            .string     = nullptr,
            .uvX        = DRAW_OFFSET_X + 24,
            .uvY        = DRAW_OFFSET_Y + 88,
            .uvWidth    = 0,
            .uvHeight   = 0,
            .posX       = CONDITION_OFFSET_X + 62,
            .posY       = CONDITION_OFFSET_Y + 91,
            .boxWidth   = 48,
            .boxHeight  = 6,
            .alignmentX = AlignmentX::CENTER,
            .alignmentY = AlignmentY::BOTTOM,
            .color      = 0,
            .layer      = 5,
            .hasShadow  = 1,
        },
    };
}